### ISSUE TITLE
Crash by itself

### ISSUE THREAD

**Issue by ghost** [thebrightspark/DefaultEnchantments#1]
I even tried updating to Forge 2747

---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 8/7/18 10:46 AM
Description: Updating screen events

java.lang.NullPointerException: Updating screen events
	at brightspark.defaultenchantments.DefaultEnchantments.getItemEnchantments(DefaultEnchantments.java:107)
	at brightspark.defaultenchantments.DefaultEnchantments.access$000(DefaultEnchantments.java:29)
	at brightspark.defaultenchantments.DefaultEnchantments$DEHandler.tryEnchant(DefaultEnchantments.java:121)
	at brightspark.defaultenchantments.DefaultEnchantments$DEHandler.itemCrafted(DefaultEnchantments.java:135)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_4_DEHandler_itemCrafted_ItemCraftedEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.firePlayerCraftingEvent(FMLCommonHandler.java:594)
	at net.minecraft.inventory.SlotCrafting.func_75208_c(SlotCrafting.java:54)
	at net.minecraft.inventory.SlotCrafting.func_190901_a(SlotCrafting.java:70)
	at net.minecraft.inventory.Container.func_184996_a(Container.java:303)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187098_a(PlayerControllerMP.java:566)
	at net.minecraft.client.gui.inventory.GuiContainer.func_184098_a(GuiContainer.java:638)
	at net.minecraft.client.gui.inventory.GuiInventory.func_184098_a(SourceFile:202)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java:392)
	at net.minecraft.client.gui.inventory.GuiInventory.func_73864_a(SourceFile:160)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1757)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at brightspark.defaultenchantments.DefaultEnchantments.getItemEnchantments(DefaultEnchantments.java:107)
	at brightspark.defaultenchantments.DefaultEnchantments.access$000(DefaultEnchantments.java:29)
	at brightspark.defaultenchantments.DefaultEnchantments$DEHandler.tryEnchant(DefaultEnchantments.java:121)
	at brightspark.defaultenchantments.DefaultEnchantments$DEHandler.itemCrafted(DefaultEnchantments.java:135)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_4_DEHandler_itemCrafted_ItemCraftedEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.firePlayerCraftingEvent(FMLCommonHandler.java:594)
	at net.minecraft.inventory.SlotCrafting.func_75208_c(SlotCrafting.java:54)
	at net.minecraft.inventory.SlotCrafting.func_190901_a(SlotCrafting.java:70)
	at net.minecraft.inventory.Container.func_184996_a(Container.java:303)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187098_a(PlayerControllerMP.java:566)
	at net.minecraft.client.gui.inventory.GuiContainer.func_184098_a(GuiContainer.java:638)
	at net.minecraft.client.gui.inventory.GuiInventory.func_184098_a(SourceFile:202)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java:392)
	at net.minecraft.client.gui.inventory.GuiInventory.func_73864_a(SourceFile:160)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)

-- Affected screen --
Details:
	Screen name: net.minecraft.client.gui.inventory.GuiInventory

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['scribbler957'/0, l='MpServer', x=759.47, y=57.00, z=244.14]]
	Chunk stats: MultiplayerChunkCache: 547, 547
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (762,4,244), Chunk: (at 10,0,4 in 47,15; contains blocks 752,0,240 to 767,255,255), Region: (1,0; contains chunks 32,0 to 63,31, blocks 512,0,0 to 1023,255,511)
	Level time: 14255 game time, 18930 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 1 total; [EntityPlayerSP['scribbler957'/0, l='MpServer', x=759.47, y=57.00, z=244.14]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2739)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:418)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Mac OS X (x86_64) version 10.13.5
	Java Version: 1.8.0_181, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 474833048 bytes (452 MB) / 1313341440 bytes (1252 MB) up to 7635730432 bytes (7282 MB)
	JVM Flags: 3 total; -Xmx8192m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.4.2729 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                  | Version      | Source                               | Signature                                |
	|:--------- |:------------------- |:------------ |:------------------------------------ |:---------------------------------------- |
	| UCHIJAAAA | minecraft           | 1.12.2       | minecraft.jar                        | None                                     |
	| UCHIJAAAA | mcp                 | 9.42         | minecraft.jar                        | None                                     |
	| UCHIJAAAA | FML                 | 8.0.99.99    | forge-1.12.2-14.23.4.2729.jar        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge               | 14.23.4.2729 | forge-1.12.2-14.23.4.2729.jar        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | defaultenchantments | 1.0.0        | defaultenchantments-1.12.2-1.0.0.jar | None                                     |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '2.1 NVIDIA-10.30.33 355.11.10.10.35.101' Renderer: 'NVIDIA GeForce GT 750M OpenGL Engine'
	Launched Version: forge-14.23.4.2729
	LWJGL: 2.9.2
	OpenGL: NVIDIA GeForce GT 750M OpenGL Engine GL version 2.1 NVIDIA-10.30.33 355.11.10.10.35.101, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-4770S CPU @ 3.10GHz

**Comment by thebrightspark** [comment]
Ah whoops, I think this is caused by either the defaultEnchantments.json not existing or the JSON file having invalid syntax. If the former, then running the game again might be alright (since it generates a new file when none is found.
However if that still doesn't work, create the file (if it's not there) and just put this in it:
`[]`

That should do it. I'll get a fix out soon when I can.

**Comment by ghost** [comment]
The first run, the mod created an empty file that didn't help. Once I added the "[]" the game became stable. Or as stable as these things become. ;)
I haven't tried populating the file and testing it yet.
Thanks

**Comment by thebrightspark** [comment]
Alright, yeah it's exactly as I thought :)
I've fixed it now (https://github.com/thebrightspark/DefaultEnchantments/commit/9836035c20c7d4477b92ac770461163ba3f7121d)
And the default file will have "[ ]" already in it.
